---
project_name: go-adsb-console

builds:
- env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  - arm
  - arm64
  goos:
  - linux
  - darwin
  flags:
  - -trimpath
  ldflags:
  - "-s -w -extldflags '-static'"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

nfpms:
- id: default
  file_name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  vendor: Bill Glover
  homepage: https://github.com/billglover/go-adsb-console
  maintainer: Bill Glover <bglover@pivotal.io>
  description: Agent to send ADSB updates to RabbitMQ exchange.
  formats:
  - deb
  - rpm
  scripts:
    postinstall: "scripts/postinstall.sh"
    preremove: "scripts/preremove.sh"
  contents:
    - src: scripts/etc/systemd/system/*
      dst: /etc/systemd/system
    - src: config_sample.yaml
      dst: /etc/go-adsb-console/config.yaml
      type: config|noreplace